server:
  port: 8080
  compression:  #vai comprimir toda resposta acima de 1024 bytes, eh para ficar mais rapido
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json #comma separated iste of MIME types should be compressed
    min-response-size: 1024 #min content-lenght value that is required for compression to be perform
  undertow:
    threads:
      worker: 64 #geralmente precisa ser alto, pelo menos 10 por CPU
      io: 4 #Uma IO thread por CPU eh um padrao razoavel

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSLL=true$serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
