mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}  #vai buscar essa variavel de ambiente, caso nao exista, usa um padrao, root neste caso
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}